# True colors
#set -g default-terminal "alacritty"
#set-option -sa terminal-overrides ",alacritty*:Tc"
set -g default-terminal "tmux-256color"
set-option -sa terminal-overrides ",xterm-256color:Tc"

# Change prefix
unbind C-b
set -g prefix C-space
bind C-space send-prefix

# Bindings
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

set -g mouse on

# Session picker in a floating popup
bind s display-popup -E "tmux list-sessions | sed -E 's/:.*$//' | fzf --reverse --header 'Pick a session' --preview 'tmux capture-pane -ep -t {}' | xargs tmux switch-client -t"
bind S command-prompt -p "New session name:" "new-session -d -s '%%' && switch-client -t '%%'"

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-logging'

# Auto-restore session on tmux start
set -g @continuum-restore 'on'

# Save and restore pane contents
set -g @resurrect-capture-pane-contents 'on'

# Initialize TPM (must be at the very bottom)
run '~/.tmux/plugins/tpm/tpm'
